services:
    dbhost:
      image: quanticschoolofbusiness/103mysql
    app:
      build: app/.
      ports: 
        - 3006:3006
      depends_on:
        - dbhost
        - redis-server
      env_file:
        - db.env
    redis-server:
      image: redis
    email:
      build: email/.
      ports: 
        - 25:25
      depends_on:
        - redis-server
      env_file:
        - email.env
    db-loader:
      build: db-loader/.
      volumes: 
        - C:/Users/Roy Quantic/OneDrive - servicePath/Files/Reviewer/MSSE/Lessons/0803/allergylab/allergy-lab-watchfolder:/mnt/watchfolder/
      environment:
        FOLDER_PATH: /mnt/watchfolder/
      env_file:
        - db.env
      depends_on:
        - dbhost